services:

  # Frontend: Nginx
  nginx:
    container_name: nginx-dev
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    image: fem37-audiophile-dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/nginx/redirects.map:/etc/nginx/redirects.map:ro
