services:

  # Frontend: Nginx
  nginx:
    container_name: fem37-nginx-dev
    restart: unless-stopped
    # Image is custom / local
    image: nginx-1.24-alpine-brotli
    command: nginx -g 'daemon off;'
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx/headers.conf:/etc/nginx/conf.d/headers.conf:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/nginx/redirects.map:/etc/nginx/redirects.map:ro
