services:

  # Frontend: Nginx-React
  nginx:
    container_name: fem37-nginx-prod
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
