FROM node:16.17.0

LABEL version="1.0"
LABEL description="Prod Image: MERN App: NodeJS"

WORKDIR /src/backend
COPY package.json /src/backend
RUN npm install && npm cache clean --force

COPY . /src/backend

EXPOSE 4000
CMD ["npm", "run", "prod"]