# Primary Stage: Build React Image
FROM node:18-alpine3.15 as primary

LABEL version="1.0"
LABEL description="Prod Image: MERN App: React"

WORKDIR /src/frontend
COPY package.json /src/frontend/
RUN npm install && npm cache clean --force

COPY . /src/frontend

# CMD ["npm", "run", "build"]
RUN npm run build



# Secondary Stage: 
FROM nginx

LABEL version="1.0"
LABEL description="Prod Image: MERN App: NGINX"

COPY --from=primary /src/frontend/public /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]