FROM nginx-1.24-alpine-brotli

LABEL version="1.0"
LABEL description="Dev Image: #37 Audiophile: NGINX"

RUN apk add nano
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]