version: "3.7"
services:
  # Backend: Node API
  node-api:
    container_name: node-api
    #image
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    #command: npm start // will override default command declared by container image
    #work_dir: /app // will override containers work dir in dockerfile
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      # Map dev source files (read-only) from local to image
      - ./Backend:/src/myApp:ro
    #env_file:
    # - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=mongo-db
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    depends_on:
      - mongo-db
  
  # Frontend: React App
  react-app:
    container_name: react-app
    #image
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports: 
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./Frontend:/src/myApp:ro
      # env_file:
      #   - ./Frontend/.env
      # environment:
    depends_on:
      - node-api
  
  # DB: MongoDB
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: unless-stopped
    #env_file:
    #  - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb-data:/data/db

  # DB: MongoDB Express - DEV ONLY
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo-db
    ports:
      - $MONGOEXP_LOCAL_PORT:$MONGOEXP_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123456
    volumes:
      - mongodb-data:/data/db

volumes:
  # Persist MongoDB Data
  mongodb-data:
    #driver: local