version: "3.7"
services:

  # Backend: Node API
  node-api:
    container_name: node-api-prod
    build:
      dockerfile: Dockerfile.prod
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    env_file:
    - ./.env.prod
    environment:
      - NODE_ENV=production
      - DB_HOST=mongo-db
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
  

  # Frontend: React App
  react-app:
    container_name: react-app-prod
    build:
      dockerfile: Dockerfile.prod
    ports: 
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    depends_on:
      node-api:
        condition: service_completed_successfully



  # NGINX
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - node-api
      - react-app
    ports:
    - 8080:80