services:

  # Backend: NodeJS Express
  node-api:
    container_name: fem32-node-api-prod
    build:
      dockerfile: ./Dockerfile
    image: fem32-nodejs-express-api
    env_file:
      - ./backend/.env.prod
    networks:
      - FEM32

  # Frontend: Nginx-React
  react-app:
    container_name: fem32-react-app-prod
    build:
      dockerfile: ./Dockerfile
    image: fem32-img-react-app
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - node-api
    networks:
      - FEM32

  # NGINX
  nginx:
    container_name: fem32-nginx-prod
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - node-api
      - react-app
    ports:
      - 8080:80
    networks:
      - FEM32

networks:
  FEM32:
