name: "FEM#36-MERN-Designo-DEV"
services:

  # Backend: Node API
  node-api:
    container_name: node-api-dev
    build:
      dockerfile: ./Dockerfile.dev
    image: img-node-api-dev
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/src/myApp:ro
    env_file:
      - ./backend/.env.dev
    depends_on:
      - mongo-db
    # networks:
    #   - container-network

    # Frontend: React App
  react-app:
    container_name: react-app-dev
    build:
      dockerfile: ./Dockerfile.dev
    image: img-react-app-dev
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./frontend:/src/myApp:ro
    env_file:
      - ./frontend/.env.dev
    depends_on:
      - node-api
    # networks:
    #   - container-network

    # DB: MongoDB
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb-data:/data/db
    # networks:
    #   - container-network

    # DB: MongoDB Express - DEV ONLY
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo-db
    ports:
      - $MONGOEXP_LOCAL_PORT:$MONGOEXP_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGOEXP_BASICAUTH_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOEXP_BASICAUTH_PASS
    volumes:
      - mongodb-data:/data/db
    # networks:
    #   - container-network

volumes:
  # Persist MongoDB Data
  mongodb-data:
    #driver: local

    # networks:
    #   container-network:
    #     name: container-network
    #     driver: bridge
