services:

  # Backend: NodeJS Express
  node-api:
    container_name: fem33-node-api-dev
    image: node:18-alpine3.17
    working_dir: /backend
    depends_on:
      - mongodb-1
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/backend:ro
    env_file:
      - ./backend/.env.dev
    command: npm start

  # Frontend: React App
  # Use 'npm start' from ./frontend to init webpack-dev-server

  # DB: MongoDB
  mongodb-1:
    container_name: fem33-mongodb-1
    image: mongo:6.0.6-custom
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb-data:/data/db
    command: --replSet rs0 --bind_ip_all --keyFile /data/mongo.key

  # Convert MongoDB from standalone to replica set
  mongo-setup:
    image: mongo:6.0.6-custom
    depends_on:
      - mongodb-1
    profiles:
      - enable-replicaset
    restart: "no"
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_REPLSET
      - MONGODB_REPLSET_NODE1
    volumes:
      - ./backend/mongo/mongo-init.sh:/data/mongo-init.sh
    command: sh /data/mongo-init.sh

  # DB: MongoDB Express
  mongo-express:
    image: mongo-express-custom
    depends_on:
      - mongodb-1
    restart: on-failure
    ports:
      - $MONGOEXP_LOCAL_PORT:$MONGOEXP_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-1
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGOEXP_BASICAUTH_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOEXP_BASICAUTH_PASS
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    name: mongodb-data
    external: true
