name: "fem33-project-feedback-app"
version: "3.7"
services:

  # Backend: NodeJS Express
  node-api:
    build:
      context: ./backend

  # Frontend: React
  react-app:
    build:
      context: ./frontend
