services:

  # Backend: NodeJS Express
  node-api:
    container_name: fem33-node-api-dev
    image: node:18-alpine3.17
    working_dir: /backend
    command: npm start
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/backend:ro
    env_file:
      - ./backend/.env.dev
    depends_on:
      - mongo-db

  # Frontend: React App
  # Use 'npm start' from ./frontend to init webpack-dev-server

  # DB: MongoDB
  mongo-db:
    container_name: fem33-mongo-db
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb-data:/data/db

  # DB: MongoDB Express
  mongo-express:
    image: mongo-express-custom
    depends_on:
      - mongo-db
    ports:
      - $MONGOEXP_LOCAL_PORT:$MONGOEXP_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGOEXP_BASICAUTH_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOEXP_BASICAUTH_PASS
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    name: mongodb-data
    external: true
