services:

  # Backend: NodeJS Express
  node-api:
    container_name: fem35-node-api-dev
    build:
      dockerfile: ./Dockerfile
    image: fem35-nodejs-express-api
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/backend:ro
    env_file:
      - ./backend/.env.dev
    depends_on:
      - mongo-db

  # Frontend: React App
  react-app:
    container_name: fem35-react-app-dev
    build:
      dockerfile: ./Dockerfile
    image: fem35-react-app
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    env_file:
      - ./frontend/.env.dev
    depends_on:
      - node-api

  # DB: MongoDB
  mongo-db:
    container_name: fem35-mongo-db
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb-data:/data/db

  # DB: MongoDB Express - DEV ONLY
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo-db
    ports:
      - $MONGOEXP_LOCAL_PORT:$MONGOEXP_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGOEXP_BASICAUTH_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOEXP_BASICAUTH_PASS
    volumes:
      - mongodb-data:/data/db

volumes:
  # Persist MongoDB Data
  mongodb-data:
